# This workflow will build a package using Gradle and then publish it to maven

name: Kotlin CI

on:
  push:
    branches:
      - 'master'
      - '0.3.x'
      - '0.4.x'
    tags-ignore:
      - '*.*'
    pull_request:
      types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build Cache
    runs-on: ubuntu-latest
    env:

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: browser-actions/setup-chrome@v1
        name: Setup Chrome
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace --info build

  release:
    name: Publish artifacts
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    env:
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -x test publish

