name: Documentation CI
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  mikbot:
    uses: kordlib/.teamcity/.github/workflows/documentation.yml@main
    with:
      main-branch: "feature/native"
